arb-dir: lib/src/l10n/arb
output-dir: lib/src/l10n/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: lib/src/l10n/untranslated_messages.json
deferred-loading: false
format: true
header: "// ignore_for_file: dart-format"
