// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1VQw9WvEwQFuMeYdDoRdxiDT_zweklw',
    appId: '1:342835125572:web:174d52fd4e8f031f320b11',
    messagingSenderId: '342835125572',
    projectId: 'flutter-presentum-example',
    authDomain: 'flutter-presentum-example.firebaseapp.com',
    storageBucket: 'flutter-presentum-example.firebasestorage.app',
    measurementId: 'G-WLJE1227E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMCGeaLfyXl6xxwYv-95nw5kDWKnD_rM',
    appId: '1:342835125572:android:2af41c5435c195c8320b11',
    messagingSenderId: '342835125572',
    projectId: 'flutter-presentum-example',
    storageBucket: 'flutter-presentum-example.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaG-kL5zswiHkS2NhACf0j0PfvC7B4uzU',
    appId: '1:342835125572:ios:831608d83b2a9569320b11',
    messagingSenderId: '342835125572',
    projectId: 'flutter-presentum-example',
    storageBucket: 'flutter-presentum-example.firebasestorage.app',
    iosBundleId: 'dev.itsezlife.presentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaG-kL5zswiHkS2NhACf0j0PfvC7B4uzU',
    appId: '1:342835125572:ios:831608d83b2a9569320b11',
    messagingSenderId: '342835125572',
    projectId: 'flutter-presentum-example',
    storageBucket: 'flutter-presentum-example.firebasestorage.app',
    iosBundleId: 'dev.itsezlife.presentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG1VQw9WvEwQFuMeYdDoRdxiDT_zweklw',
    appId: '1:342835125572:web:1a2329f3a4302c06320b11',
    messagingSenderId: '342835125572',
    projectId: 'flutter-presentum-example',
    authDomain: 'flutter-presentum-example.firebaseapp.com',
    storageBucket: 'flutter-presentum-example.firebasestorage.app',
    measurementId: 'G-Z20X9GZTTB',
  );
}
